### ISSUE TITLE
Undefined constant 'IMG_JPG'

### ISSUE THREAD

**Issue by hizt** [Gregwar/Image#108]
Undefined constant 'IMG_JPG'
FILE:  vendor/gregwar/image/Gregwar/Image/Image.php 　LINE: 285

when php uninstall "GD" extension , but "Imagick" installed

**Comment by Soullivaneuh** [comment]
You just closed the issue. Maybe can you explain how did you solve it?

**Comment by hizt** [comment]
install "GD" extension for php

**Comment by Soullivaneuh** [comment]
@Gregwar Maybe we can add a prevent error message for missing gd-extension library.

**Comment by Gregwar** [comment]
Actually, I was hoping this (https://github.com/Gregwar/Image/blob/master/composer.json#L16) would do the job

The problem is that these constants are in static initialization:
https://github.com/Gregwar/Image/blob/master/Adapter/GD.php#L10

A solution would be defaulting it to null and populating it in the constructor (where the gd check and exception already exists)
